# Generated by Django 4.2.7 on 2024-03-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosts',
            name='image',
        ),
    ]
