# Generated by Django 4.2.7 on 2024-03-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0002_remove_boosts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boosts',
            name='user',
        ),
    ]
