# Generated by Django 4.2.7 on 2024-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_boosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boosts',
        ),
        migrations.AddField(
            model_name='user',
            name='auto_click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tap_ability',
            field=models.IntegerField(default=0),
        ),
    ]
