# Generated by Django 4.2.7 on 2024-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_boosts_user_auto_click_user_tap_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tap_ability',
            field=models.IntegerField(default=1),
        ),
    ]
