# Generated by Django 4.2.7 on 2024-03-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_tap_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='end_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='miner',
            field=models.IntegerField(default=0),
        ),
    ]
