# Generated by Django 4.2.7 on 2024-03-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='boost',
        ),
    ]
